const ResponseDataState = Object.freeze({
    FORM_INPUT_IN_PROGRESS: 'FORM_INPUT',
    FORM_INPUT_COMPLETE: 'FORM_INPUT_COMPLETE',
    DATA_FETCHING: 'DATA_FETCHING',
    DATA_FETCH_SUCCESS: 'DATA_FETCH_SUCCESS',
    DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
    API_ERROR: 'API_ERROR',
});

export default ResponseDataState;